from src.core.handlers.exceptions import *


class DuplicateUserException(DuplicateResourceException): ...


class InvalidUserLoginException(AuthException): ...


class UserPermissionDeniedException(PermissionDeniedException): ...


class DetailNotFoundException(ResourceNotFoundException): ...


class TransactionsNotFoundException(ResourceNotFoundException): ...


class UserDatabaseOperationError(DatabaseOperationError): ...


class UsernameValidationException(ValidationException): ...


class AmountValidationException(ValidationException): ...
